### PR TITLE
feat: refactor using `@react-sping/web` and remove prop-types usage

### PR DESCRIPTION
**Pull request by idindrakusuma**
### Brief

Hello @WinterCore 👋 First of all, thank you for creating this awesome package. I'm using your package for year now and working smoothly until I'm upgraded my project to Next.js 13.x.x in the beginning of the year. In development, I don't see any error but when I built my PR and deployed, I found the issue because `prop-types` no longer support in `Next.js@v13` TypeScript. 

So, I decided to re-create this component in my local component by use interface instead of using `prop-types` and also use the latest package recommendation from `@react-spring` https://www.react-spring.dev/docs/getting-started. It's working perfectly! 😄  
 
I'm super excited to share my latest changes in this pull request! These changes include refactoring main component, adding `.prettierc.js` and also updating `README.md`. I've also tested these changes thoroughly to ensure they meet our project's high standards for quality and performance. Thank you for taking the time to review my work, and I look forward to your feedback!

### Notable Changes
- [x] use latest package recommendation `@react-spring/web`
- [x] update package.json version to beta
- [x] export interface `TextTransitionProps`
- [x] update readme.md
- [x] remove `prop-types` usage
- [x] add `.prettierrc.js` 

### Result

Codesanbox Link: https://codesandbox.io/p/sandbox/react-text-transition-improvement-q268i9?file=README.md

https://user-images.githubusercontent.com/10141928/230700196-95700d51-ad67-472b-8377-ace9c334ff17.mov

Local Development Proof

https://user-images.githubusercontent.com/10141928/230700225-5abffe53-6069-4c01-8278-5f0ed54a5919.mov

### CODE REVIEW

**Comment by idindrakusuma** [comment]
looking feedback from all of you guys 😄 

@WinterCore
@whiteand 
@phwt
@coopbri

thank you!

**Comment by WinterCore** [comment]
Hey @idindrakusuma, Thank you so much for taking the time to make this PR.
I was honestly thinking of archiving this repo because I don't have the motivation or the time to maintain it anymore, so you kinda saved it 😄 

Everything looks good. I tested it locally and it works without any issues.
I'll merge this and push the new version to npm.

Thanks again 🙌

**Comment by WinterCore** [comment]
btw, would you be interested in maintaining this long-term? I can give you push access if so.

**Comment by idindrakusuma** [comment]
> Hey @idindrakusuma, Thank you so much for taking the time to make this PR. I was honestly thinking of archiving this repo because I don't have the motivation or the time to maintain it anymore, so you kinda saved it 😄
> 
> Everything looks good. I tested it locally and it works without any issues. I'll merge this and push the new version to npm.
> 
> Thanks again 🙌

Wow! That was fast 😃 
Thank you 🙌

**Comment by idindrakusuma** [comment]
> btw, would you be interested in maintaining this long-term? I can give you push access if so.

Sure! Because I'm still using this package and the other one too! 😄 I'm happy to help!

**Pull request merged**
